version: '3.8'

services:
  wewiseapi:
    image: wewiseapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDB="mongodb+srv://pietronignacio:corner321@wewise.dpixtmv.mongodb.net/?retryWrites=true&w=majority&appName=WeWise"
