# Utiliza la imagen oficial de .NET para construir el proyecto
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia los archivos de la solución y restaura las dependencias
COPY wwbo.sln .
COPY Application/Application.csproj Application/
COPY Domain/Domain.csproj Domain/
COPY Infrastructure/Infrastructure.csproj Infrastructure/
COPY Presentation/Presentation.csproj Presentation/
RUN dotnet restore "Presentation/Presentation.csproj"

# Copia el resto de los archivos y construye el proyecto
COPY . .
WORKDIR /src/Presentation
RUN dotnet build "Presentation.csproj" -c Release -o /app/build

# Publica la aplicación
FROM build AS publish
RUN dotnet publish "Presentation.csproj" -c Release -o /app/publish

# Configura el entorno de producción
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Presentation.dll"]
